language: node_js
node_js:
  - "11"

cache: npm

script:
  - npm test && npm run build

deploy:
  - provider: s3
    skip_cleanup: true
    endpoint: https://nyc3.digitaloceanspaces.com
    acl: public_read
    access_key_id: $SPACES_ACCESS_KEY
    secret_access_key: $SPACES_SECRET
    bucket: "mustachebash-public"
    local_dir: dist
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    endpoint: https://nyc3.digitaloceanspaces.com
    access_key_id: $SPACES_ACCESS_KEY
    secret_access_key: $SPACES_SECRET
    bucket: "mustachebash-private"
    local_dir: templates
    upload-dir: templates
    on:
      branch: master
  - provider: s3
    skip_cleanup: true
    endpoint: https://nyc3.digitaloceanspaces.com
    acl: public_read
    access_key_id: $SPACES_ACCESS_KEY
    secret_access_key: $SPACES_SECRET
    bucket: "mustachebash-stage"
    local_dir: dist
    on:
      branch: stage
  - provider: s3
    skip_cleanup: true
    endpoint: https://nyc3.digitaloceanspaces.com
    access_key_id: $SPACES_ACCESS_KEY
    secret_access_key: $SPACES_SECRET
    bucket: "mustachebash-stage"
    local_dir: templates
    upload-dir: templates
    on:
      branch: stage

branches:
  only:
    - master
    - stage
